name: Dockerize React Application
on: push
jobs:
  build-container:
    name: Build Docker container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Publish to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
          registry: ghcr.io
          repository: ${{ github.repository }}/service-mapper
          tags: latest, ${{ github.run_number }}